# B9.x Problems
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<h2>Problem B9.1</h2>
    </header>

A flywheel (I = 50.0 kgm$^2$) starting from rest acquires an angular velocity of +200.0 rad/s while subject to a constant torque from a motor for 5.0 s. 

1. What is the angular acceleration of the flywheel? 
2. What is the torque?


This problem is a slightly modified version from OpenStax. Access for free at [https://openstax.org/books/university-physics-volume-1/pages/10-problems](https://openstax.org/books/university-physics-volume-1/pages/10-problems)

In [1]:
%reset -f
#----------------
# Part 1
#----------------
w0 = 0.0
w1 = 200.0
dt = 5.0

alpha = (w1 - w0)/dt

print('Angular acceleration: '+str(alpha))

#----------------
# Part 2
#----------------
I = 50.0

T = I*alpha



Angular acceleration: 40.0


<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<h2>Problem B9.2</h2>
    </header>

Suppose you exert a force of 180 N tangential to a 0.280 m radius, 75.0 kg grindstone (a solid disk). 

1. What magnitude of the torque is exerted? 
2. What is the magnitude of the angular acceleration assuming negligible opposing friction? 
3. What is the magnitude of the angular acceleration if there is an opposing frictional force of 50.0 N exerted 1.50 cm from the axis?

This problem is a slightly modified version from OpenStax. Access for free at [https://openstax.org/books/university-physics-volume-1/pages/10-problems](https://openstax.org/books/university-physics-volume-1/pages/10-problems)

In [2]:
%reset -f
#----------------
# Part 1
#----------------
F1 = 180.0
R1 = 0.280

T1 = R1*F1   #angle is 90 degrees
print('Torque: '+str(T1))

#----------------
# Part 2
#----------------
M = 75.0

I = 0.5*M*R1**2

A = T1/I
print('Angular acceleration: '+str(A))

#----------------
# Part 3
#----------------
F2 = 50.0
R2 = 0.015
T2 = R2*F2

T_net = T1 - T2
A_net = T_net/I
print('Angular acceleration: '+str(A_net))

Torque: 50.400000000000006
Angular acceleration: 17.142857142857142
Angular acceleration: 16.887755102040817


<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<h2>Problem B9.3</h2>
    </header>

A torque of 50.0 Nm is applied to a grinding wheel (I = 20.0 kgm$^2$) for 20.0 s. 

1. If it starts from rest, what is the magnitude of the angular velocity of the grinding wheel after the torque is removed? 
2. Through what angle does the wheel move while the torque is applied?

This problem is a slightly modified version from OpenStax. Access for free at [https://openstax.org/books/university-physics-volume-1/pages/10-problems](https://openstax.org/books/university-physics-volume-1/pages/10-problems)

In [3]:
%reset -f
#----------------
# Part 1
#----------------
T = 50.0
I = 20.0
dt = 20.0
w0 = 0.0

A = T/I
w1 = w0 + A*dt

print('Angular speed: '+str(w1))

#----------------
# Part 2
#----------------
dtheta = w0*dt + 0.5*A*dt**2

print('Angular distance (in radians): '+str(dtheta))

Angular speed: 50.0
Angular distance (in radians): 500.0


<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<h2>Problem B9.4</h2>
    </header>

A uniform cylindrical grinding wheel of mass 50.0 kg and diameter 1.0 m is turned on by an electric motor. The friction in the bearings is negligible. 

1. What torque must be applied to the wheel to bring it from rest to +120.0 rev/min in 20.0 revolutions? 
2. A tool whose coefficient of kinetic friction with the wheel is 0.60 is pressed perpendicularly against the wheel with a force of 40.0 N. What torque must be supplied by the motor to keep the wheel rotating at a constant angular velocity?

This problem is a slightly modified version from OpenStax. Access for free at [https://openstax.org/books/university-physics-volume-1/pages/10-problems](https://openstax.org/books/university-physics-volume-1/pages/10-problems)

In [4]:
%reset -f
import numpy as np

#----------------
# Part 1
#----------------
M = 50.0
R = 1.0
w0 = 0.0
w1 = (120.0)*(2*np.pi/1.0)*(1.0/60.0) 
dtheta = (20.0)*(2*np.pi)

I = 0.5*M*R**2
A = (w1**2 - w0**2)/(2*dtheta)

T = I*A

print('Torque: '+str(T))

#----------------
# Part 2
#----------------
# applied torque must counter the frictional torque 

F2 = 40.0
mu = 0.60

Ff = mu*F2
Tf = R*Ff

print('Applied Torque: '+str(Tf))

Torque: 15.70796326794896
Applied Torque: 24.0


<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<h2>Problem B9.5</h2>
    </header>

A pulley of moment of inertia 2.0 kgm$^2$ is mounted on a wall as shown in the following figure. Light strings are wrapped around two circumferences of the pulley and weights are attached. Assume the following data:  $r_1 = 50.0~\textrm{cm}$, $r_2 = 20.0~\textrm{cm}$, $m_1 = 1.0~\textrm{kg}$, and $m_2 = 2.0~\textrm{kg}$, what are 

1. the angular acceleration of the pulley?
2. the linear acceleration of the weights? 

<img src="P9.4.png" width="300">

This problem is a slightly modified version from OpenStax. Access for free at [https://openstax.org/books/university-physics-volume-1/pages/10-problems](https://openstax.org/books/university-physics-volume-1/pages/10-problems)

In [5]:
%reset -f
import sympy as sym

I = 2.0
R1 = 0.500
R2 = 0.200
M1 = 1.0
M2 = 2.0
g = 9.81

#unknowns
A1 = sym.Symbol('A1')
A2 = sym.Symbol('A2')
F_T1 = sym.Symbol('F_T1')
F_T2 = sym.Symbol('F_T2')
A = sym.Symbol('A')

# Positive up for 1, CW for pulley, down for 2
#linear N2 on blocks
eq1 = M1*A1 - F_T1 + M1*g
eq2 = M2*A2 + F_T2 - M2*g

#rotational N2 on pulley
eq3 = I*A + F_T1*R1 - F_T2*R2

#relating accelerations
eq4 = A1 - R1*A
eq5 = A2 - R2*A

sol = sym.solve((eq1,eq2,eq3,eq4,eq5),(A1,A2,F_T1,F_T2,A))

print(sol)

{A1: -0.210515021459227, A2: -0.0842060085836910, F_T1: 9.59948497854077, F_T2: 19.7884120171674, A: -0.421030042918455}


<hr style="height:2px;border-width:0;color:gray;background-color:gray">